server:
  port: 8082

spring:
  application:
    name: todo
  datasource:
    url: ${TODO_DATASOURCE_URL}
    username: ${TODO_DATASOURCE_USERNAME}
    password: ${TODO_DATASOURCE_PASSWORD}
  rabbitmq:
    host: ${RABBIT_URL}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

rabbitmq:
  user-deleted:
    exchange: event.user.deleted.exchange
    queue: event.user.deleted.todo.queue
    key: event.user.deleted.key
  todo-deleted:
    exchange: event.user.deleted.exchange
    key: event.user.deleted.key
  todo-updated:
    exchange: event.user.updated.exchange
    key: event.user.updated.key

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info