server:
  port: 8082

spring:
  application:
    name: todo
  datasource:
    url: ${TODO_DATASOURCE_URL}
    username: ${TODO_DATASOURCE_USERNAME}
    password: ${TODO_DATASOURCE_PASSWORD}
  rabbitmq:
    host: ${RABBIT_URL}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

auth:
  service:
    url: ${AUTH_SERVICE_URL}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false

rabbit:
  exchanges:
    notify: "notify.event"
    dead: "notify.dead.event"
  queue:
    schedule:
      created:
        key: "schedule.created.key"
      deleted:
        key: "schedule.deleted.key"
    user:
      deleted:
        key: "user.deleted.key"
    notify:
      dead:
        key: "notify.dead.key"

management:
  endpoints:
    web:
      exposure:
        include: health,info