spring:
  datasource:
    url: jdbc:mysql://localhost:3308/todo_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

auth:
  service:
    url: http://localhost:8081
