openapi:
  services:
    - name: auth
      url: http://localhost:8081
    - name: todo
      url: http://localhost:8082
    - name: notify
      url: http://localhost:8083
    - name: focus
      url: http://localhost:8084

auth:
  service:
    url: http://localhost:8081

todo:
  service:
    url: http://localhost:8082

notify:
  service:
    url: http://localhost:8083

focus:
  service:
    url: http://localhost:8084

frontend:
  url: http://localhost:5173

jwt:
  secret: this-is-a-very-very-long-and-strong-secret-key-for-jwt-signing