server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth
              uri: ${AUTH_SERVICE_URL}
              predicates:
                - Path=/auth/**
              filters:
                - name: JwtAuthFilter

            - id: todo
              uri: ${TODO_SERVICE_URL}
              predicates:
                - Path=/todo/**
              filters:
                - name: JwtAuthFilter

            - id: auth-docs
              uri: ${AUTH_SERVICE_URL}
              predicates:
                - Path=/docs/auth/**
              filters:
                - StripPrefix=2

            - id: todo-docs
              uri: ${TODO_SERVICE_URL}
              predicates:
                - Path=/docs/todo/**
              filters:
                - StripPrefix=2

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /docs/auth/v3/api-docs
      - name: Todo Service
        url: /docs/todo/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info