server:
  port: 8081

spring:
  application:
    name: auth
  data:
    redis:
      host: ${AUTH_REDIS_HOST}
      port: ${AUTH_REDIS_PORT}
  datasource:
    url: ${AUTH_DATASOURCE_URL}
    username: ${AUTH_DATASOURCE_USERNAME}
    password: ${AUTH_DATASOURCE_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  accessExpiration: 3600000
  refreshExpiration: 2592000000

management:
  endpoints:
    web:
      exposure:
        include: health,info