server:
  port: 8083

spring:
  application:
    name: notify
  data:
    redis:
      host: ${NOTIFY_REDIS_HOST}
      port: ${NOTIFY_REDIS_PORT}
  datasource:
    url: ${NOTIFY_DATASOURCE_URL}
    username: ${NOTIFY_DATASOURCE_USERNAME}
    password: ${NOTIFY_DATASOURCE_PASSWORD}
  rabbitmq:
    host: ${RABBIT_URL}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

rabbit:
  exchanges:
      notify: "notify.event"
      dead: "notify.dead.event"
  queue:
    schedule:
      created:
        name: "schedule.created.queue"
        key: "schedule.created.key"
      deleted:
        name: "schedule.deleted.queue"
        key: "schedule.deleted.key"
    user:
      deleted:
        name: "user.deleted.queue"
        key: "user.deleted.key"
    notify:
      dead:
        name: "notify.dead.queue"
        key: "notify.dead.key"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info